#!/usr/bin/env bash
#
# Arch Linux install — generated by the *nix Install Guides manual walkthrough.
#
# READ THIS BEFORE RUNNING IT. It repartitions /dev/nvme0n1 and does not
# ask twice. Nothing on that disk survives.
#
# The markdown guide explains why each command is here. This is the same
# sequence with the prose stripped out.

set -Eeuo pipefail
set -x        # debug verbosity: echo every command before running it

trap 'echo "FAILED at line $LINENO. The disk may be half-configured." >&2' ERR

# A generated script that runs without you having read it is exactly the
# failure mode this project exists to avoid.
read -rp "Have you read this script in full? Type YES to continue: " ok
[[ "$ok" == "YES" ]] || { echo "Stopping."; exit 1; }

lsblk
read -rp "Destroy everything on /dev/nvme0n1? Type the disk path to confirm: " confirm
[[ "$confirm" == "/dev/nvme0n1" ]] || { echo "Mismatch. Stopping."; exit 1; }

# ── block 1 ───────────────────────────────────────────────────────────
ls /sys/firmware/efi && echo UEFI   # confirms firmware mode

# Wireless, if you need it:
iwctl station wlan0 connect YOUR_SSID

ping -c3 archlinux.org
timedatectl set-ntp true

# ── block 2 ───────────────────────────────────────────────────────────
lsblk                       # identify the disk by size and model. Twice.

# ── block 3 ───────────────────────────────────────────────────────────
gdisk /dev/nvme0n1
#   o → new GPT (destroys the existing table)
#   n → 1 → +1G → type ef00   (EFI system partition)
#   n → 2 → rest        → type 8300   (Linux filesystem)
#   w → write
#
# 1 GiB rather than 512 MiB: a unified kernel image bundles the kernel
# and initramfs into one EFI file, and two of those plus a fallback
# does not fit in 512 MiB.

# ── block 4 ───────────────────────────────────────────────────────────
cryptsetup luksFormat --type luks2 --pbkdf argon2id /dev/nvme0n1p2
cryptsetup open /dev/nvme0n1p2 cryptroot

# ── block 5 ───────────────────────────────────────────────────────────
mkfs.fat -F32 /dev/nvme0n1p1
mkfs.btrfs -f /dev/mapper/cryptroot

mount /dev/mapper/cryptroot /mnt
btrfs subvolume create /mnt/@
btrfs subvolume create /mnt/@home
btrfs subvolume create /mnt/@log
btrfs subvolume create /mnt/@pkg
btrfs subvolume create /mnt/@snapshots
umount /mnt

O="noatime,compress=zstd:3,space_cache=v2"
mount -o $O,subvol=@          /dev/mapper/cryptroot /mnt
mkdir -p /mnt/{home,var/log,var/cache/pacman/pkg,.snapshots,boot}
mount -o $O,subvol=@home      /dev/mapper/cryptroot /mnt/home
mount -o $O,subvol=@log       /dev/mapper/cryptroot /mnt/var/log
mount -o $O,subvol=@pkg       /dev/mapper/cryptroot /mnt/var/cache/pacman/pkg
mount -o $O,subvol=@snapshots /dev/mapper/cryptroot /mnt/.snapshots
mount /dev/nvme0n1p1 /mnt/boot

# ── block 6 ───────────────────────────────────────────────────────────
pacstrap -K /mnt \
    base linux-firmware sudo vim man-db man-pages texinfo linux linux-headers linux-lts linux-lts-headers btrfs-progs cryptsetup intel-ucode networkmanager sbctl efibootmgr zram-generator

genfstab -U /mnt >> /mnt/etc/fstab
cat /mnt/etc/fstab          # read it before you trust it
arch-chroot /mnt

# ── block 7 ───────────────────────────────────────────────────────────
ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
hwclock --systohc

sed -i 's/^#en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "KEYMAP=us" > /etc/vconsole.conf

echo "archbox" > /etc/hostname
cat >> /etc/hosts <<'EOF'
127.0.0.1   localhost
::1         localhost
127.0.1.1   archbox.localdomain archbox
EOF

passwd                                     # root password
useradd -m -G wheel -s /bin/bash you
passwd you
EDITOR=vim visudo                          # uncomment %wheel ALL=(ALL:ALL) ALL

# ── block 8 ───────────────────────────────────────────────────────────
vim /etc/mkinitcpio.conf
# HOOKS=(base systemd autodetect microcode modconf kms keyboard \
#        sd-vconsole block sd-encrypt filesystems fsck)
#
# sd-encrypt must come BEFORE filesystems, and keyboard before
# sd-encrypt — otherwise you get a passphrase prompt you cannot type
# into, which looks exactly like a broken install.

mkinitcpio -P

# ── block 9 ───────────────────────────────────────────────────────────
UUID=$(blkid -s UUID -o value /dev/nvme0n1p2)
echo "rd.luks.name=$UUID=cryptroot root=/dev/mapper/cryptroot rootflags=subvol=@ rw" > /etc/kernel/cmdline

# Turn on the unified image preset
sed -i "s|^#\?ALL_config|ALL_config|" /etc/mkinitcpio.d/linux.preset
mkinitcpio -P

# ── block 10 ──────────────────────────────────────────────────────────
sbctl status                 # firmware must be in Setup Mode
sbctl create-keys
sbctl enroll-keys -m         # -m keeps the Microsoft OEM certificates
sbctl sign -s /boot/EFI/Linux/arch-linux.efi
sbctl verify

# ── block 11 ──────────────────────────────────────────────────────────
systemctl enable NetworkManager

cat > /etc/systemd/zram-generator.conf <<'EOF'
[zram0]
zram-size = min(ram / 2, 8192)
compression-algorithm = zstd
EOF

# ── block 12 ──────────────────────────────────────────────────────────
exit
umount -R /mnt
cryptsetup close cryptroot
reboot

# ── block 13 ──────────────────────────────────────────────────────────
sudo pacman -S --needed \
    hyprland waybar wofi xdg-desktop-portal-hyprland qt5-wayland qt6-wayland polkit-kde-agent pipewire pipewire-pulse pipewire-alsa wireplumber ttf-jetbrains-mono-nerd ufw snapper snap-pac git

# ── block 14 ──────────────────────────────────────────────────────────
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable
sudo systemctl enable ufw

# ── block 15 ──────────────────────────────────────────────────────────
sudo umount /.snapshots && sudo rm -rf /.snapshots
sudo snapper -c root create-config /
sudo btrfs subvolume delete /.snapshots
sudo mkdir /.snapshots && sudo mount -a
sudo systemctl enable --now snapper-timeline.timer snapper-cleanup.timer

# ── block 16 ──────────────────────────────────────────────────────────
git config --global user.name "Your Name"
git config --global user.email "you@example.com"
git config --global init.defaultBranch main

# ── block 17 ──────────────────────────────────────────────────────────
curl -fsSL https://raw.githubusercontent.com/tilas01/Unix-SIT/main/scripts/install-security-suite.sh -o install.sh
less install.sh          # read it before running it as root
sudo bash install.sh --only libre-otp,anti-ducky,anti-evil-maid,kernel-watcher,scarecrow,aur-guard

# ── block 18 ──────────────────────────────────────────────────────────
cat | sudo tee /etc/udev/rules.d/99-buskill.rules <<'EOF'
SUBSYSTEM=="usb", ACTION=="remove", ENV{ID_MODEL}=="BusKill*", RUN+="/usr/bin/loginctl lock-sessions"
EOF
sudo udevadm control --reload-rules

echo "Done. Read the markdown guide for what to do after the first boot."